# Feature scaling with sklearn - Exercise

Real estate is one of those examples that every regression course goes through as it is extremely easy to understand and there is a (almost always) certain causal relationship to be found.

The data is located in the file: 'real_estate_price_size_year.csv'. 

You are expected to create a multiple linear regression (similar to the one in the lecture), using the new data. This exercise is very similar to a previous one. This time, however, **please standardize the data**.

Apart from that, please:
-  Display the intercept and coefficient(s)
-  Find the R-squared and Adjusted R-squared
-  Compare the R-squared and the Adjusted R-squared
-  Compare the R-squared of this regression and the simple linear regression where only 'size' was used
-  Using the model make a prediction about an apartment with size 750 sq.ft. from 2009
-  Find the univariate (or multivariate if you wish - see the article) p-values of the two variables. What can you say about them?
-  Create a summary table with your findings

The dependent variable is 'price', while the independent variables are 'size' and 'year'.

## Import the relevant libraries

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

E:\softwares\softwares_installation\anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
E:\softwares\softwares_installation\anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


## Load the data

In [2]:
data = pd.read_csv('real_estate_price_size_year.csv')

In [3]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

## Create the regression

### Declare the dependent and the independent variables

In [4]:
y=data['price']
x=data[['size','year']]

### Scale the inputs

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() # empty standardscaler object, in other words 
scaler.fit(x)
x_scaled = scaler.transform(x) # Transforms the unscaled inputs using the information contained in the scalar object(feature-wise), the data is standardized
x_scaled

array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206],
       [-1.23371919,  1.14763808],
       [ 2.19844528,  0.51006137],
       [ 1.42498884, -0.76509206],
       [-0.937209  , -1.40266877],
       [-0.95171405,  0.51006137],
       [-0.78328682, -1.40266877],
       [-0.57603328,  1.14763808],
       [-0.53467702, -0.76509206],
       [ 0.69939906, -0.76509206],
       [ 3.33780001, -0.76509206],
       [-0.53467702,  0.51006137],
       [ 0.52699137,  1.14763808],
       [ 1.51100715, -1.40266877],
       [ 1.77668568, -1.40266877],
       [-0.54810263,  1.14763808],
       [-0.77276222, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.58943055,  1.14763808],
       [-0.78365788,  0.51006137],
       [-1.02322731,  0.51006137],
       [ 1.19557293,  0.51006137],
       [-1.12884431,  0.51006137],
       [-1.10378093, -0.76509206],
       [ 0.84424715,  1.14763808],
       [-0.95171405,  1.14763808],
       [ 1.62279723,  0.51006137],
       [-0.58004747,

### Regression

In [9]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### Find the intercept

In [10]:
reg.intercept_

292289.4701599997

### Find the coefficients

In [11]:
reg.coef_

array([67501.57614152, 13724.39708231])

### Calculate the R-squared

In [12]:
reg.score(x_scaled, y)

0.7764803683276793

### Calculate the Adjusted R-squared

In [13]:
n = x_scaled.shape[0]
p = x_scaled.shape[1]
r2 = reg.score(x_scaled, y)
r2Adj = 1- (1-r2)*(n-1)/(n-p-1)

In [14]:
r2Adj

0.77187171612825

### Compare the R-squared and the Adjusted R-squared

It seems the the R-squared is only slightly larger than the Adjusted R-squared, implying that we were not penalized a lot for the inclusion of 2 independent variables.

### Compare the Adjusted R-squared with the R-squared of the simple linear regression

Comparing the Adjusted R-squared with the R-squared of the simple linear regression (when only 'size' was used - a couple of lectures ago), we realize that 'Year' is not bringing too much value to the result.

### Making predictions

Find the predicted price of an apartment that has a size of 750 sq.ft. from 2009.

In [19]:
reg.predict(scaler.transform([[750, 2009]]))

array([258330.34465995])

### Calculate the univariate p-values of the variables

In [20]:
from sklearn.feature_selection import f_regression

In [21]:
f_regression(x_scaled, y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [22]:
p_values = f_regression(x_scaled, y)[1]

In [23]:
p_values.round(3)

array([0.   , 0.357])

### Create a summary table with your findings

In [26]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['features'])
reg_summary['Coefficients'] = reg.coef_
reg_summary['Intercept'] = reg.intercept_
reg_summary['p-values'] = p_values.round(3)
reg_summary

features  Coefficients     Intercept  p-values
0     size  67501.576142  292289.47016     0.000
1     year  13724.397082  292289.47016     0.357

It seems that 'Year' is not event significant, therefore we should remove it from the model.